name: 'guestfish'
description: 'Execute a guestfish script'
inputs:
  fish_script:  # id of input
    description: 'guestfish script contents'
    required: true
runs:
  using: 'docker'
  image: 'ghcr.io/xcape-inc/docker-guestfs:master'
  entrypoint: /usr/local/bin/guestfish_use_script.sh
  args:
    - ${{ inputs.fish_script }}
